### PR TITLE
Fix active tab color in Colors demo

### LINKED ISSUE #1017: Colors demo has awkward active tab color
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

## Expected vs actual result:

When viewing the Colors demo (at `/demo/colors`), the active color palette name completely blends in with the background.

Screenshot 2023-10-02 at 11 48 29 AM

The active color name should still be legible.

## Steps to reproduce:
1. Run Gallery
1. Click on "Colors" demo inside "Styles & Other" list
1. Change active color palettes and observe that you cannot read the name of the selected color

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by craiglabenz**
## Description

Screenshot 2023-10-02 at 1 59 22 PM

Fixes #1017 

## Tests

No tests - UI change only.

## Issues
Fixes #

---

>**Note**: Please find the development and releasing instructions at https://github.com/flutter/gallery#development

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
That's definitely much better. Probably best to use the color scheme's onPrimary color.

FTR: the demo we'd like developers to see is /flutter/samples/tree/main/material_3_demo

File: lib/demos/reference/colors_demo.dart [hunk 1]
```diff
@@ -245,6 +245,7 @@ class ColorsDemo extends StatelessWidget {
             tabs: [
               for (final palette in palettes) Tab(text: palette.name),
             ],
+            labelColor: Colors.white,
```
Comment (guidezpl) [inline lib/demos/reference/colors_demo.dart:248]:
```suggestion
            labelColor: Theme.of(context).colorScheme.onPrimary,
```

**Review by guidezpl — APPROVED** [review]
