### PR TITLE
l10n updates & cleanup

### LINKED ISSUE #79: Generated plural translations are incorrect
**Describe the bug**
All locales have the values from the default `en` locale for the plural strings. Check the `gallery_localizations.dart` file or generate the files via `grinder`

Example string names: `shrineCartItemCount`, `shrineScreenReaderCart`

Example code from `gallery_localizations.dart` form the `pl` locale.
```
...

@override
String shrineCartItemCount(int quantity) {
  return intl.Intl.pluralLogic(
    quantity,
    locale: _localeName,
    zero: 'NO ITEMS',
    one: '1 ITEM',
    other: '${quantity} ITEMS',
  );
}

@override
String get shrineCartClearButtonCaption => 'WYCZYŚĆ KOSZYK';

...
```

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
[✓] Flutter (Channel master, v1.16.3, on Mac OS X 10.15.3 19D76, locale pl-PL)
    • Flutter version 1.16.3 at /Users/kawa/development/flutter
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kawa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kawa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM G965F                  • 228a58df34047ece • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554    • android-x86    • Android 5.0.2 (API 21) (emulator)
    • Chrome                    • chrome           • web-javascript • Google Chrome 80.0.3987.149
    • Web Server                • web-server       • web-javascript • Flutter Tools
```

**To Reproduce**
Generate the translations via `flutter pub run grinder l10n` and check the generated plural translation.

**Expected behavior**
Translations for plural strings should be taken from all locales, not the default `en`

### PR DESCRIPTION
**Pull request by guidezpl**
- Import latest translations from TC
- Use latest gen_l10n script, which puts translations in individual dart files instead of `gallery_localizations.dart` 
- Add `pub get` to `grinder` l10n command

Miscellaneous fixes
- Fix link in about dialog 
- Fix MaterialApp title being different from web page title (previously `Gallery`, now `Flutter Gallery`)
- Fix relative links in docs

Fixes #79

### CODE REVIEW

File: tool/l10n_cli/l10n_cli.dart [hunk 1]
```diff
@@ -13,7 +13,7 @@ const _intlHeader = '''
 <!--
   This file was automatically generated.
   Please do not edit it manually.
-  It was based on gallery/lib/src/l10n/intl_en.arb.
+  It was based on lib/l10n/intl_en.arb.
```
Comment (clocksmith) [inline tool/l10n_cli/l10n_cli.dart:16]: Not: It is based
