### PR TITLE
Set the status bars style correctly

### LINKED ISSUE #82: Status bar theme sometimes incorrect
**Describe the bug**
The status bar theme is sometimes incorrect

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
[✓] Flutter (Channel unimplemented-message, v1.16.2-pre.5, on Mac OS X 10.15.4 19E266, locale
    en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.6)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

**To Reproduce**
1. Navigate to studies and back home
2. Observe that in some studies the status bar theme is incorrect
3. Observe that sometimes, upon returning home, the status bar theme is incorrect

**Expected behavior**
The status bar theme matches that of the underlying content.

**Screenshots**

Correct:
Screenshot 2020-04-01 at 15 18 11

Incorrect:

Screenshot 2020-04-01 at 15 18 03

Screenshot 2020-04-01 at 15 17 52

### PR DESCRIPTION
**Pull request by guidezpl**
Sets the status bar style correctly everywhere by using an `AnnotatedRegion` for the home screen pages and `AppBar`/`AppBarTheme` for the studies.

Plus some cleanup + start animating the settings icon before the page animation

Closes #82 

Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-06 at 20 03 47

### CODE REVIEW

File: lib/studies/shrine/theme.dart [hunk 1]
```diff
@@ -21,6 +21,7 @@ IconThemeData _customIconTheme(IconThemeData original) {
 ThemeData _buildShrineTheme() {
   final base = ThemeData.light();
   return base.copyWith(
+    appBarTheme: const AppBarTheme(brightness: Brightness.light, elevation: 0),
```
Comment (rami-a) [inline lib/studies/shrine/theme.dart:24]: Does Fortnightly need any updates?

Comment (guidezpl) [reply lib/studies/shrine/theme.dart:24]: Nope, Fortnightly already had an AppBar + AppBarTheme
